# -*- coding: utf-8 -*-
"""Delinquency_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_BqoKHBeEFvR3KE2jMoxl_iZiB2NE7L

# New Notebook
"""

# STEP 1: Install necessary packages
!pip install -q imbalanced-learn joblib

# STEP 2: Import required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
import joblib

# STEP 3: Upload dataset
from google.colab import files
uploaded = files.upload()

# STEP 4: Load dataset
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

# Drop Customer_ID column if present
if 'Customer_ID' in df.columns:
    df.drop(columns=['Customer_ID'], inplace=True)

# Separate features and target
X = df.drop(columns=['Delinquent_Account'])
y = df['Delinquent_Account']

# STEP 5: Identify column types
categorical_cols = X.select_dtypes(include='object').columns.tolist()
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

# STEP 6: Preprocessing pipeline for SMOTE
preprocessor_for_smote = ColumnTransformer([
    ('num', SimpleImputer(strategy='median'), numerical_cols),
    ('cat', Pipeline([
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('onehot', OneHotEncoder(handle_unknown='ignore'))
    ]), categorical_cols)
])

# Fit and transform the data before SMOTE
X_encoded = preprocessor_for_smote.fit_transform(X)

# STEP 7: Apply SMOTE to balance the data
smote = SMOTE(random_state=42)
X_bal, y_bal = smote.fit_resample(X_encoded, y)

# STEP 8: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_bal, y_bal, test_size=0.2, random_state=42)

# STEP 9: Train Random Forest model
model = RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42)
model.fit(X_train, y_train)

# STEP 10: Evaluate the model
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print("=== Evaluation Results ===")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC AUC Score:", roc_auc_score(y_test, y_prob))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# STEP 11: Save and download the model
joblib.dump(model, "delinquency_model.joblib")
files.download("delinquency_model.joblib")

